### ISSUE TITLE
AWS CLI installed on Cloud9 broken

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/aws-hpc-tutorials#26]
### Issue

Latest aws-cli gives the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python3.6/site-packages/awscli/clidriver.py", line 36, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/lib/python3.6/site-packages/awscli/help.py", line 23, in <module>
    from botocore.docs.bcdoc import docevents
ImportError: cannot import name 'docevents'
```
This is easy to reproduce:
1. Spin up Cloud9 instance
2. Run `aws s3 ls`

Ta-da

See https://github.com/boto/boto3/issues/2596

### Solution

Upgrade AWS CLI

```
pip-3.6 install --upgrade awscli
```

**Comment by kraman-aws** [comment]
Yes you need to do it under "sudo" though
